/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [OrderID]
      ,[Order_OrderDetailsItemID]
      ,[Order_ActivationCodeID]
      ,[Order_UserID]
      ,[OrderFirstUseDate]
      ,[OrderValidTillDate]
      ,[OrderLogistics_EntityID]
      ,[OrderRenewal_OrderID]
      ,[OrderTotalPriceDue]
      ,[OrderBalanceAmountReceived]
      ,[OrderBalanceReceivedDate]
      ,[Order_OrderTypeID]
      ,[Order_MicID]
      ,[OrderDepositAmountDue]
      ,[OrderDepositAmountReceived]
      ,[OrderDepositReceivedDate]
      ,[Order_InvoiceID]
      ,[OrderInstitutionValidTillDate]
  FROM [BSTPub_DEV].[dbo].[OrderMain]
  where Order_UserID='129578'
